version: '3.8'

services:
  api:
    image: squarestory/inspecto_api:latest
    restart: always
    env_file: ./backend/.env
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - NODE_ENV=production
      - PORT=10000
    networks:
      - inspecto
    ports:
      - "10000:10000"

networks:
  inspecto:
    driver: bridge