name: inspecto

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - inspecto

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - PORT=10000
    networks:
      - inspecto
    ports:
      - "10000:10000"
    depends_on:
      - redis

volumes:
  redis_data:
networks:
  inspecto:
    driver: bridge