name: Deploy to Render

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code (optional if building Docker locally)
      - uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push image
      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inspecto_api:latest

      # Trigger Render deploy
      - name: Trigger Render Deploy
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/inspecto_api:latest || true
            echo "Stopping and removing old container..."
            docker stop inspecto_api || true
            docker rm inspecto_api || true
            echo "Running new container..."
            docker run -d --name inspecto_api -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/inspecto_api:latest
