name: Deploy Backend to AWS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inspecto-backend:latest

      - name: Setup SSH Key
        run: |
                echo "$SSH_KEY" > private_key.pem
                chmod 600 private_key.pem
        env:
                SSH_KEY: ${{ secrets.SSH_KEY }}
        
      - name: Add Server to Known Hosts
        run: |
                mkdir -p ~/.ssh
                ssh-keyscan -H ${{ secrets.PRODUCTION_SERVER_IP }} >> ~/.ssh/known_hosts
        
      - name: Deploy to AWS EC2
        env:
                SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
        run: |
                ssh -i private_key.pem ubuntu@$SERVER_IP << 'EOF'
                  sudo apt-get update
                  cd ~/Inspecto
                  docker-compose pull --no-cache
                  docker-compose up -d --force-recreate
                EOF

      - name: Clean Up SSH Key
        run: |
            rm -f private_key.pem