name: Deploy Backend to AWS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inspecto-backend:latest

      - name: Setup SSH Key
        run: |
            echo "${{ secrets.SSH_KEY }}" > private_key.pem
            chmod 600 private_key.pem

      - name: Test SSH Connection
        env:
            SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
        run: |
            ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
            ssh -i private_key.pem ubuntu@$SERVER_IP echo "SSH connection successful"

      - name: Deploy to AWS EC2
        env:
            SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
        run: |
            set -e
            ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
            ssh -i private_key.pem ubuntu@$SERVER_IP << 'EOF'
              sudo apt-get update
              sudo apt-get install -y docker-compose
              if [ ! -d "~/Inspecto" ]; then
                git clone https://github.com/square-story/Inspecto.git ~/Inspecto
              fi
              cd ~/Inspecto
              docker-compose pull
              docker-compose up -d
            EOF

      - name: Clean Up SSH Key
        run: |
            rm -f private_key.pem